const STORAGE_KEY = 'taskflow_tasks_v1';
const THEME_KEY = 'taskflow_theme';

let tasks = [];
let activeFilter = 'all';
let selectedTaskId = null;
let toastTimer;

const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const todayISO = () => new Date().toISOString().slice(0, 10);
const dateFromOffset = (offset) => { const date = new Date(); date.setHours(12, 0, 0, 0); date.setDate(date.getDate() + offset); return date.toISOString().slice(0, 10); };
const formatDate = (dateString, withYear = false) => { if (!dateString) return 'No due date'; const date = new Date(`${dateString}T12:00:00`); return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', ...(withYear ? { year: 'numeric' } : {}) }); };
const formatFullDate = (dateString) => new Date(`${dateString}T12:00:00`).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
const escapeHTML = (value = '') => String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]));
const priorityRank = { high: 0, medium: 1, low: 2 };

function sampleTasks() {
  return [
    { id: crypto.randomUUID(), title: 'Complete DSA Assignment', description: 'Finish tree traversal problems and upload the solution PDF.', subject: 'Data Structures', category: 'Assignment', priority: 'high', dueDate: dateFromOffset(2), dueTime: '18:00', completed: false, important: true, createdAt: new Date().toISOString() },
    { id: crypto.randomUUID(), title: 'Prepare OS Unit 2 Notes', description: 'Review process synchronization and make concise revision notes.', subject: 'Operating Systems', category: 'Assignment', priority: 'medium', dueDate: dateFromOffset(0), dueTime: '20:00', completed: false, important: false, createdAt: new Date().toISOString() },
    { id: crypto.randomUUID(), title: 'CN Lab Submission', description: 'Test the socket programming experiment and submit the report.', subject: 'Computer Networks', category: 'Project', priority: 'high', dueDate: dateFromOffset(-1), dueTime: '23:00', completed: false, important: true, createdAt: new Date().toISOString() },
    { id: crypto.randomUUID(), title: 'Database Mini Project', description: 'Add the search queries and finalize the ER diagram.', subject: 'Database Management', category: 'Project', priority: 'medium', dueDate: dateFromOffset(6), dueTime: '17:00', completed: false, important: false, createdAt: new Date().toISOString() },
    { id: crypto.randomUUID(), title: 'Web Development Practical', description: 'Build the responsive form validation page for the lab.', subject: 'Web Development', category: 'Assignment', priority: 'low', dueDate: dateFromOffset(4), dueTime: '15:30', completed: true, important: false, createdAt: new Date().toISOString() },
    { id: crypto.randomUUID(), title: 'Prepare for Internal Exam', description: 'Revise chapters 1 to 4 and practice last year questions.', subject: 'Operating Systems', category: 'Exam', priority: 'high', dueDate: dateFromOffset(10), dueTime: '09:00', completed: false, important: true, createdAt: new Date().toISOString() }
  ];
}

function saveTasks() { localStorage.setItem(STORAGE_KEY, JSON.stringify(tasks)); }
function loadTasks() { try { const stored = JSON.parse(localStorage.getItem(STORAGE_KEY)); tasks = Array.isArray(stored) ? stored : sampleTasks(); } catch { tasks = sampleTasks(); } if (!localStorage.getItem(STORAGE_KEY)) saveTasks(); }
function isOverdue(task) { return !task.completed && task.dueDate < todayISO(); }
function isToday(task) { return task.dueDate === todayISO(); }
function isUpcoming(task) { return !task.completed && task.dueDate > todayISO(); }
function dueLabel(task) { if (isOverdue(task)) return `<span class="due-label overdue"><i data-lucide="triangle-alert"></i>Overdue · ${formatDate(task.dueDate)}</span>`; if (isToday(task)) return `<span class="due-label today"><i data-lucide="clock-3"></i>Due today${task.dueTime ? ` · ${task.dueTime}` : ''}</span>`; return `<span class="due-label"><i data-lucide="calendar-days"></i>Due ${formatDate(task.dueDate)}${task.dueTime ? ` · ${task.dueTime}` : ''}</span>`; }

function getFilteredTasks() {
  const query = ($('#taskSearch')?.value || $('#globalSearch')?.value || '').trim().toLowerCase();
  const subject = $('#subjectFilter')?.value || 'all';
  const priority = $('#priorityFilter')?.value || 'all';
  let result = tasks.filter((task) => {
    const matchesFilter = activeFilter === 'all' || (activeFilter === 'today' && isToday(task)) || (activeFilter === 'upcoming' && isUpcoming(task)) || (activeFilter === 'completed' && task.completed) || (activeFilter === 'pending' && !task.completed) || (activeFilter === 'important' && task.priority === 'high') || (activeFilter === 'overdue' && isOverdue(task));
    const matchesQuery = !query || `${task.title} ${task.description} ${task.subject}`.toLowerCase().includes(query);
    return matchesFilter && matchesQuery && (subject === 'all' || task.subject === subject) && (priority === 'all' || task.priority === priority);
  });
  const sort = $('#sortSelect')?.value || 'due';
  result.sort((a, b) => sort === 'priority' ? priorityRank[a.priority] - priorityRank[b.priority] : sort === 'created' ? new Date(b.createdAt) - new Date(a.createdAt) : (a.dueDate || '9999').localeCompare(b.dueDate || '9999'));
  return result;
}

function taskMarkup(task) {
  return `<article class="task-item ${task.completed ? 'is-complete' : ''}" data-task-id="${task.id}"><input class="task-check" type="checkbox" ${task.completed ? 'checked' : ''} aria-label="Mark ${escapeHTML(task.title)} complete" data-toggle-task="${task.id}"><div class="task-main" data-open-details="${task.id}"><div class="task-title"><strong>${escapeHTML(task.title)}</strong>${task.priority === 'high' ? '<i class="important-star" data-lucide="star" aria-label="High priority"></i>' : ''}</div><p class="task-description">${escapeHTML(task.description || 'No description added.')}</p><div class="task-meta"><span class="subject-label">${escapeHTML(task.subject)}</span><span class="category-label">${escapeHTML(task.category)}</span><span class="badge priority-${task.priority}">${task.priority} priority</span>${dueLabel(task)}</div></div><div class="task-actions"><button class="icon-button edit-task" data-edit-task="${task.id}" type="button" aria-label="Edit ${escapeHTML(task.title)}" title="Edit task"><i data-lucide="pencil"></i></button><button class="icon-button delete-task" data-delete-task="${task.id}" type="button" aria-label="Delete ${escapeHTML(task.title)}" title="Delete task"><i data-lucide="trash-2"></i></button></div></article>`;
}

function renderTasks() {
  const filtered = getFilteredTasks();
  const list = $('#taskList');
  if (!filtered.length) { list.innerHTML = `<div class="empty-state"><span class="empty-icon"><i data-lucide="inbox"></i></span><strong>No tasks found</strong><p>You're all caught up! Add a new task to get started.</p><button class="button button-soft" data-open-task type="button"><i data-lucide="plus"></i>Add task</button></div>`; } else list.innerHTML = filtered.map(taskMarkup).join('');
  updateSectionTitle();
  renderMiniLists();
  updateSubjectFilter();
  lucide.createIcons();
}

function updateSectionTitle() { const labels = { all: 'My Tasks', today: "Today's Tasks", upcoming: 'Upcoming Tasks', completed: 'Completed Tasks', pending: 'Pending Tasks', important: 'Important Tasks', overdue: 'Overdue Tasks' }; $('#taskSectionTitle').textContent = labels[activeFilter]; $$('.filter-tab').forEach((tab) => tab.classList.toggle('active', tab.dataset.filter === activeFilter)); }
function miniMarkup(task, dotClass = '') { return `<div class="mini-task"><span class="mini-task-dot ${dotClass}"></span><div class="mini-task-copy" data-open-details="${task.id}"><strong>${escapeHTML(task.title)}</strong><span>${escapeHTML(task.subject)} · ${isToday(task) ? 'Today' : formatDate(task.dueDate)}</span></div></div>`; }
function renderMiniLists() { const important = tasks.filter((task) => task.priority === 'high' && !task.completed).sort((a, b) => a.dueDate.localeCompare(b.dueDate)).slice(0, 3); const today = tasks.filter(isToday).sort((a, b) => Number(a.completed) - Number(b.completed)); const upcoming = tasks.filter(isUpcoming).sort((a, b) => a.dueDate.localeCompare(b.dueDate)).slice(0, 3); $('#importantList').innerHTML = important.length ? important.map((task) => miniMarkup(task, 'red')).join('') : '<p class="mini-empty">No high-priority tasks right now.</p>'; $('#todayList').innerHTML = today.length ? today.slice(0, 4).map((task) => miniMarkup(task, task.completed ? 'green' : '')).join('') : '<p class="mini-empty">Nothing due today. Nice work.</p>'; $('#upcomingList').innerHTML = upcoming.length ? upcoming.map((task) => miniMarkup(task)).join('') : '<p class="mini-empty">Your schedule is clear.</p>'; }

function updateSubjectFilter() { const select = $('#subjectFilter'); const current = select.value; const subjects = [...new Set(tasks.map((task) => task.subject).filter(Boolean))].sort(); select.innerHTML = '<option value="all">All subjects</option>' + subjects.map((subject) => `<option value="${escapeHTML(subject)}">${escapeHTML(subject)}</option>`).join(''); select.value = subjects.includes(current) ? current : 'all'; }
function calculateStatistics() { const total = tasks.length; const completed = tasks.filter((task) => task.completed).length; const pending = total - completed; const overdue = tasks.filter(isOverdue).length; const percent = (value) => total ? Math.round(value / total * 100) : 0; $('#totalStat').textContent = total; $('#completedStat').textContent = completed; $('#pendingStat').textContent = pending; $('#overdueStat').textContent = overdue; $('#totalTrend').textContent = total ? '100%' : '0%'; $('#completedTrend').textContent = `${percent(completed)}%`; $('#pendingTrend').textContent = `${percent(pending)}%`; $('#overdueTrend').textContent = overdue ? 'Needs attention' : 'All clear'; $('#totalProgress').style.width = '100%'; $('#completedProgress').style.width = `${percent(completed)}%`; $('#pendingProgress').style.width = `${percent(pending)}%`; $('#overdueProgress').style.width = overdue ? '100%' : '0%'; $('#allCount').textContent = total; $('#allFilterCount').textContent = total; }
function calculateProgress() { const total = tasks.length; const completed = tasks.filter((task) => task.completed).length; const percent = total ? Math.round(completed / total * 100) : 0; $('#progressPercent').textContent = `${percent}%`; $('#ringPercent').textContent = `${percent}%`; $('#progressCompleted').textContent = completed; $('#progressPending').textContent = total - completed; $('#studyProgressBar').style.width = `${percent}%`; $('#progressRing').style.background = `conic-gradient(var(--primary) ${percent * 3.6}deg, #e8e9f2 ${percent * 3.6}deg)`; $('#progressHeadline').textContent = percent === 100 ? 'Perfect score' : percent > 0 ? 'Good momentum' : "Let's get started"; }
function renderSubjects() { const subjects = ['Data Structures', 'Operating Systems', 'Computer Networks', 'Database Management', 'Web Development']; $('#subjectGrid').innerHTML = subjects.map((subject) => { const related = tasks.filter((task) => task.subject.toLowerCase() === subject.toLowerCase()); const completed = related.filter((task) => task.completed).length; const percent = related.length ? Math.round(completed / related.length * 100) : 0; return `<article class="subject-card"><h4>${subject}</h4><p><strong>${related.length}</strong> tasks · <strong>${completed}</strong> done</p><div class="subject-progress"><i style="width: ${percent}%"></i></div></article>`; }).join(''); }
function renderDashboard() { calculateStatistics(); calculateProgress(); renderSubjects(); renderTasks(); }

function openModal(id) { const modal = $(`#${id}`); modal.hidden = false; document.body.style.overflow = 'hidden'; const focusTarget = modal.querySelector('input, button'); if (focusTarget) setTimeout(() => focusTarget.focus(), 50); }
function closeModal(id) { const modal = $(`#${id}`); modal.hidden = true; if (!$$('.modal-backdrop:not([hidden])').length) document.body.style.overflow = ''; }
function openTaskForm(task = null) { $('#taskForm').reset(); $('#editingTaskId').value = task?.id || ''; $('#taskModalTitle').textContent = task ? 'Edit task' : 'Add a new task'; $('#submitTaskText').textContent = task ? 'Save changes' : 'Add Task'; $('#taskPriority').value = task?.priority || 'medium'; $('#taskCategory').value = task?.category || 'Assignment'; if (task) { $('#taskTitle').value = task.title; $('#taskDescription').value = task.description; $('#taskSubject').value = task.subject; $('#taskDueDate').value = task.dueDate; $('#taskDueTime').value = task.dueTime || ''; } else $('#taskDueDate').value = todayISO(); openModal('taskModal'); }
function addTask(formData) { tasks.unshift({ id: crypto.randomUUID(), ...formData, completed: false, important: formData.priority === 'high', createdAt: new Date().toISOString() }); saveTasks(); renderDashboard(); showToast('Task added to your workspace.'); }
function updateTask(id, formData) { const index = tasks.findIndex((task) => task.id === id); if (index === -1) return; tasks[index] = { ...tasks[index], ...formData, important: formData.priority === 'high' }; saveTasks(); renderDashboard(); showToast('Task changes saved.'); }
function toggleTask(id) { const task = tasks.find((item) => item.id === id); if (!task) return; task.completed = !task.completed; saveTasks(); renderDashboard(); showToast(task.completed ? 'Task marked complete.' : 'Task moved back to pending.'); }
function requestDelete(id) { selectedTaskId = id; openModal('confirmModal'); }
function deleteTask() { if (!selectedTaskId) return; tasks = tasks.filter((task) => task.id !== selectedTaskId); saveTasks(); closeModal('confirmModal'); closeModal('detailsModal'); selectedTaskId = null; renderDashboard(); showToast('Task deleted.'); }
function showDetails(id) { const task = tasks.find((item) => item.id === id); if (!task) return; selectedTaskId = id; $('#detailsTitle').textContent = task.title; $('#detailsContent').innerHTML = `<div class="details-body"><div class="details-description">${escapeHTML(task.description || 'No description added for this task.')}</div><div class="detail-cell"><span>Subject</span><strong>${escapeHTML(task.subject)}</strong></div><div class="detail-cell"><span>Category</span><strong>${escapeHTML(task.category)}</strong></div><div class="detail-cell"><span>Priority</span><strong class="badge priority-${task.priority}">${task.priority} priority</strong></div><div class="detail-cell"><span>Status</span><strong>${task.completed ? 'Completed' : isOverdue(task) ? 'Overdue' : 'In progress'}</strong></div><div class="detail-cell"><span>Created</span><strong>${formatDate(task.createdAt.slice(0, 10), true)}</strong></div><div class="detail-cell"><span>Due</span><strong>${formatFullDate(task.dueDate)}${task.dueTime ? ` at ${task.dueTime}` : ''}</strong></div></div>`; $('#detailsComplete').innerHTML = task.completed ? '<i data-lucide="rotate-ccw"></i>Mark as pending' : '<i data-lucide="check"></i>Mark complete'; lucide.createIcons(); openModal('detailsModal'); }
function showToast(message) { $('#toastMessage').textContent = message; $('#toast').classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => $('#toast').classList.remove('show'), 2800); }

function setupEvents() {
  document.addEventListener('click', (event) => { const openButton = event.target.closest('[data-open-task]'); if (openButton) openTaskForm(); const closeButton = event.target.closest('[data-close-modal]'); if (closeButton) closeModal(closeButton.dataset.closeModal); const filterButton = event.target.closest('[data-filter]'); if (filterButton) { activeFilter = filterButton.dataset.filter; renderTasks(); } const jumpButton = event.target.closest('[data-filter-jump]'); if (jumpButton) { activeFilter = jumpButton.dataset.filterJump; renderTasks(); $('#tasksSection').scrollIntoView({ behavior: 'smooth', block: 'start' }); } const detailsButton = event.target.closest('[data-open-details]'); if (detailsButton) showDetails(detailsButton.dataset.openDetails); const editButton = event.target.closest('[data-edit-task]'); if (editButton) { const task = tasks.find((item) => item.id === editButton.dataset.editTask); if (task) openTaskForm(task); } const deleteButton = event.target.closest('[data-delete-task]'); if (deleteButton) requestDelete(deleteButton.dataset.deleteTask); });
  document.addEventListener('change', (event) => { if (event.target.matches('[data-toggle-task]')) toggleTask(event.target.dataset.toggleTask); });
  ['taskSearch', 'subjectFilter', 'priorityFilter', 'sortSelect'].forEach((id) => $(`#${id}`).addEventListener('input', renderTasks));
  $('#globalSearch').addEventListener('input', () => { $('#taskSearch').value = $('#globalSearch').value; activeFilter = 'all'; renderTasks(); });
  $('#taskForm').addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.target); const formData = { title: form.get('title')?.trim() || $('#taskTitle').value.trim(), description: $('#taskDescription').value.trim(), subject: $('#taskSubject').value.trim(), category: $('#taskCategory').value, priority: $('#taskPriority').value, dueDate: $('#taskDueDate').value, dueTime: $('#taskDueTime').value }; if (!formData.title || !formData.subject || !formData.dueDate) { $('#titleError').textContent = !formData.title ? 'Please add a task title.' : ''; return; } const id = $('#editingTaskId').value; id ? updateTask(id, formData) : addTask(formData); closeModal('taskModal'); });
  $('#confirmDelete').addEventListener('click', deleteTask); $('#detailsEdit').addEventListener('click', () => { const task = tasks.find((item) => item.id === selectedTaskId); closeModal('detailsModal'); if (task) openTaskForm(task); }); $('#detailsComplete').addEventListener('click', () => { if (selectedTaskId) { toggleTask(selectedTaskId); showDetails(selectedTaskId); } });
  $('#openSidebar').addEventListener('click', () => { $('#sidebar').classList.add('open'); $('#sidebarOverlay').classList.add('visible'); }); $('#closeSidebar').addEventListener('click', closeSidebar); $('#sidebarOverlay').addEventListener('click', closeSidebar); $$('.nav-item').forEach((item) => item.addEventListener('click', () => { $$('.nav-item').forEach((nav) => nav.classList.remove('active')); item.classList.add('active'); if (item.dataset.view !== 'dashboard' && item.dataset.view !== 'settings') { activeFilter = item.dataset.view; renderTasks(); $('#tasksSection').scrollIntoView({ behavior: 'smooth', block: 'start' }); } if (item.dataset.view === 'dashboard') { activeFilter = 'all'; renderTasks(); } closeSidebar(); }));
  $('#notificationButton').addEventListener('click', () => { const overdue = tasks.filter(isOverdue).length; showToast(overdue ? `You have ${overdue} overdue task${overdue === 1 ? '' : 's'}.` : 'You are all caught up.'); });
  $$('.modal-backdrop').forEach((modal) => modal.addEventListener('click', (event) => { if (event.target === modal) closeModal(modal.id); })); document.addEventListener('keydown', (event) => { if (event.key === 'Escape') $$('.modal-backdrop:not([hidden])').forEach((modal) => closeModal(modal.id)); });
}
function closeSidebar() { $('#sidebar').classList.remove('open'); $('#sidebarOverlay').classList.remove('visible'); }
function setupTheme() { if (localStorage.getItem(THEME_KEY) === 'dark') document.body.classList.add('dark'); const settingsButton = document.querySelector('[data-view="settings"]'); settingsButton.addEventListener('click', () => { document.body.classList.toggle('dark'); localStorage.setItem(THEME_KEY, document.body.classList.contains('dark') ? 'dark' : 'light'); showToast(`${document.body.classList.contains('dark') ? 'Dark' : 'Light'} mode enabled.`); }); }
function init() { loadTasks(); $('#currentDate').textContent = new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }); setupTheme(); setupEvents(); renderDashboard(); lucide.createIcons(); }

document.addEventListener('DOMContentLoaded', init);
